// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AllblogspageDocumentDataSlicesSlice = AllBlogsSlice;

/**
 * Content for Allblogspage documents
 */
interface AllblogspageDocumentData {
  /**
   * Title field in *Allblogspage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: allblogspage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Allblogspage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: allblogspage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AllblogspageDocumentDataSlicesSlice> /**
   * Meta Description field in *Allblogspage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: allblogspage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Allblogspage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: allblogspage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Allblogspage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: allblogspage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Allblogspage document from Prismic
 *
 * - **API ID**: `allblogspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AllblogspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AllblogspageDocumentData>,
    "allblogspage",
    Lang
  >;

/**
 * Item in *Footer → Services Footer*
 */
export interface FooterDocumentDataServicesFooterItem {
  /**
   * Label field in *Footer → Services Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.services_footer[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Official Info Footer*
 */
export interface FooterDocumentDataOfficialInfoFooterItem {
  /**
   * Label1 field in *Footer → Official Info Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.official_info_footer[].label1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label1: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Services Footer field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.services_footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services_footer: prismic.GroupField<
    Simplify<FooterDocumentDataServicesFooterItem>
  >;

  /**
   * Official Info Footer field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.official_info_footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  official_info_footer: prismic.GroupField<
    Simplify<FooterDocumentDataOfficialInfoFooterItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | JoinourmissionSlice
  | AboutusSlice
  | ContactUsSlice
  | BlogSlice
  | Web3MarketingGuideSlice
  | OurServicesSlice
  | Hero2Slice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type LandingpageDocumentDataSlicesSlice =
  | LandingpageSection4Slice
  | LandingpageSection3Slice
  | Landingpagesection2Slice
  | LandingpageHeroSlice;

/**
 * Content for Landingpage documents
 */
interface LandingpageDocumentData {
  /**
   * Title field in *Landingpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Landingpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingpageDocumentDataSlicesSlice> /**
   * Meta Description field in *Landingpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landingpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landingpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landingpage document from Prismic
 *
 * - **API ID**: `landingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingpageDocumentData>,
    "landingpage",
    Lang
  >;

type MainarticleDocumentDataSlicesSlice = never;

/**
 * Content for MainArticle documents
 */
interface MainarticleDocumentData {
  /**
   * Heading field in *MainArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * blogimage field in *MainArticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.blogimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogimage: prismic.ImageField<never>;

  /**
   * blogdescription field in *MainArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.blogdescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogdescription: prismic.RichTextField;

  /**
   * blogmaindescription field in *MainArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.blogmaindescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogmaindescription: prismic.RichTextField;

  /**
   * publishdate field in *MainArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.publishdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  publishdate: prismic.KeyTextField;

  /**
   * Slice Zone field in *MainArticle*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MainarticleDocumentDataSlicesSlice> /**
   * Meta Description field in *MainArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mainarticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *MainArticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainarticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *MainArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mainarticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * MainArticle document from Prismic
 *
 * - **API ID**: `mainarticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainarticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MainarticleDocumentData>,
    "mainarticle",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TrendingarticleDocumentDataSlicesSlice = never;

/**
 * Content for TrendingArticle documents
 */
interface TrendingarticleDocumentData {
  /**
   * Heading field in *TrendingArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * blogimage field in *TrendingArticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.blogimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogimage: prismic.ImageField<never>;

  /**
   * blogdescription field in *TrendingArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.blogdescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogdescription: prismic.RichTextField;

  /**
   * blogmaindescription field in *TrendingArticle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.blogmaindescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogmaindescription: prismic.RichTextField;

  /**
   * publishdate field in *TrendingArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.publishdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  publishdate: prismic.KeyTextField;

  /**
   * Slice Zone field in *TrendingArticle*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TrendingarticleDocumentDataSlicesSlice> /**
   * Meta Description field in *TrendingArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: trendingarticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TrendingArticle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trendingarticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *TrendingArticle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: trendingarticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * TrendingArticle document from Prismic
 *
 * - **API ID**: `trendingarticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrendingarticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TrendingarticleDocumentData>,
    "trendingarticle",
    Lang
  >;

export type AllDocumentTypes =
  | AllblogspageDocument
  | FooterDocument
  | HomepageDocument
  | LandingpageDocument
  | MainarticleDocument
  | SettingsDocument
  | TrendingarticleDocument;

/**
 * Primary content in *Aboutus → Primary*
 */
export interface AboutusSliceDefaultPrimary {
  /**
   * Heading field in *Aboutus → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Aboutus → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * extendedDescription field in *Aboutus → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.primary.extendeddescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  extendeddescription: prismic.RichTextField;
}

/**
 * Default variation for Aboutus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Aboutus*
 */
type AboutusSliceVariation = AboutusSliceDefault;

/**
 * Aboutus Shared Slice
 *
 * - **API ID**: `aboutus`
 * - **Description**: Aboutus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutusSlice = prismic.SharedSlice<
  "aboutus",
  AboutusSliceVariation
>;

/**
 * Primary content in *AllBlogs → Primary*
 */
export interface AllBlogsSliceDefaultPrimary {
  /**
   * Heading field in *AllBlogs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: all_blogs.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *AllBlogs → Items*
 */
export interface AllBlogsSliceDefaultItem {
  /**
   * TrendingArticle field in *AllBlogs → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: all_blogs.items[].trendingarticle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trendingarticle: prismic.ContentRelationshipField<"trendingarticle">;
}

/**
 * Default variation for AllBlogs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllBlogsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AllBlogsSliceDefaultPrimary>,
  Simplify<AllBlogsSliceDefaultItem>
>;

/**
 * Slice variation for *AllBlogs*
 */
type AllBlogsSliceVariation = AllBlogsSliceDefault;

/**
 * AllBlogs Shared Slice
 *
 * - **API ID**: `all_blogs`
 * - **Description**: AllBlogs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllBlogsSlice = prismic.SharedSlice<
  "all_blogs",
  AllBlogsSliceVariation
>;

/**
 * Primary content in *Blog → Primary*
 */
export interface BlogSliceDefaultPrimary {
  /**
   * Heading field in *Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subHeading field in *Blog → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * MainArticle field in *Blog → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.primary.mainarticle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mainarticle: prismic.ContentRelationshipField<"mainarticle">;
}

/**
 * Primary content in *Blog → Items*
 */
export interface BlogSliceDefaultItem {
  /**
   * TrendingArticle field in *Blog → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].trendingarticle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  trendingarticle: prismic.ContentRelationshipField<"trendingarticle">;
}

/**
 * Default variation for Blog Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  Simplify<BlogSliceDefaultItem>
>;

/**
 * Slice variation for *Blog*
 */
type BlogSliceVariation = BlogSliceDefault;

/**
 * Blog Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Blog
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;

/**
 * Primary content in *ContactUs → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * Heading field in *ContactUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subHeading field in *ContactUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Description field in *ContactUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ContactUs → Items*
 */
export interface ContactUsSliceDefaultItem {
  /**
   * features field in *ContactUs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.items[].features
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  features: prismic.RichTextField;
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsSliceDefaultPrimary>,
  Simplify<ContactUsSliceDefaultItem>
>;

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault;

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSlice = prismic.SharedSlice<
  "contact_us",
  ContactUsSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *TextBesideImage → Primary*
 */
export interface Hero2SliceDefaultPrimary {
  /**
   * title field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * AboutUs variation for TextBesideImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextBesideImage → Primary*
 */
export interface Hero2SliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *TextBesideImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Image Right variation for TextBesideImage Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<Hero2SliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *TextBesideImage*
 */
type Hero2SliceVariation = Hero2SliceDefault | Hero2SliceImageRight;

/**
 * TextBesideImage Shared Slice
 *
 * - **API ID**: `hero_2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2Slice = prismic.SharedSlice<"hero_2", Hero2SliceVariation>;

/**
 * Primary content in *Joinourmission → Primary*
 */
export interface JoinourmissionSliceDefaultPrimary {
  /**
   * Heading field in *Joinourmission → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: joinourmission.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Joinourmission → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: joinourmission.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * subHeading field in *Joinourmission → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: joinourmission.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * ButtonLink field in *Joinourmission → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: joinourmission.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;

  /**
   * subDescription field in *Joinourmission → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: joinourmission.primary.subdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subdescription: prismic.RichTextField;
}

/**
 * Default variation for Joinourmission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinourmissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JoinourmissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Joinourmission*
 */
type JoinourmissionSliceVariation = JoinourmissionSliceDefault;

/**
 * Joinourmission Shared Slice
 *
 * - **API ID**: `joinourmission`
 * - **Description**: Joinourmission
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinourmissionSlice = prismic.SharedSlice<
  "joinourmission",
  JoinourmissionSliceVariation
>;

/**
 * Primary content in *LandingpageHero → Primary*
 */
export interface LandingpageHeroSliceDefaultPrimary {
  /**
   * Heading field in *LandingpageHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *LandingpageHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for LandingpageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingpageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandingpageHero*
 */
type LandingpageHeroSliceVariation = LandingpageHeroSliceDefault;

/**
 * LandingpageHero Shared Slice
 *
 * - **API ID**: `landingpage_hero`
 * - **Description**: LandingpageHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageHeroSlice = prismic.SharedSlice<
  "landingpage_hero",
  LandingpageHeroSliceVariation
>;

/**
 * Primary content in *LandingpageSection3 → Primary*
 */
export interface LandingpageSection3SliceDefaultPrimary {
  /**
   * Heading field in *LandingpageSection3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section3.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *LandingpageSection3 → Items*
 */
export interface LandingpageSection3SliceDefaultItem {
  /**
   * subHeading field in *LandingpageSection3 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section3.items[].subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * subDescription field in *LandingpageSection3 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section3.items[].subdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subdescription: prismic.RichTextField;
}

/**
 * Default variation for LandingpageSection3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageSection3SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingpageSection3SliceDefaultPrimary>,
  Simplify<LandingpageSection3SliceDefaultItem>
>;

/**
 * Slice variation for *LandingpageSection3*
 */
type LandingpageSection3SliceVariation = LandingpageSection3SliceDefault;

/**
 * LandingpageSection3 Shared Slice
 *
 * - **API ID**: `landingpage_section3`
 * - **Description**: LandingpageSection3
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageSection3Slice = prismic.SharedSlice<
  "landingpage_section3",
  LandingpageSection3SliceVariation
>;

/**
 * Primary content in *LandingpageSection4 → Primary*
 */
export interface LandingpageSection4SliceDefaultPrimary {
  /**
   * Heading field in *LandingpageSection4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section4.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *LandingpageSection4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section4.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * subHeading field in *LandingpageSection4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section4.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * subDescription field in *LandingpageSection4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage_section4.primary.subdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subdescription: prismic.RichTextField;
}

/**
 * Default variation for LandingpageSection4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageSection4SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingpageSection4SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandingpageSection4*
 */
type LandingpageSection4SliceVariation = LandingpageSection4SliceDefault;

/**
 * LandingpageSection4 Shared Slice
 *
 * - **API ID**: `landingpage_section4`
 * - **Description**: LandingpageSection4
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingpageSection4Slice = prismic.SharedSlice<
  "landingpage_section4",
  LandingpageSection4SliceVariation
>;

/**
 * Primary content in *Landingpagesection2 → Primary*
 */
export interface Landingpagesection2SliceDefaultPrimary {
  /**
   * Heading field in *Landingpagesection2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpagesection2.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Landingpagesection2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpagesection2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * subHeading field in *Landingpagesection2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpagesection2.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * subDescription field in *Landingpagesection2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpagesection2.primary.subdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subdescription: prismic.RichTextField;
}

/**
 * Default variation for Landingpagesection2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Landingpagesection2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Landingpagesection2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Landingpagesection2*
 */
type Landingpagesection2SliceVariation = Landingpagesection2SliceDefault;

/**
 * Landingpagesection2 Shared Slice
 *
 * - **API ID**: `landingpagesection2`
 * - **Description**: Landingpagesection2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Landingpagesection2Slice = prismic.SharedSlice<
  "landingpagesection2",
  Landingpagesection2SliceVariation
>;

/**
 * Primary content in *OurServices → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
  /**
   * Heading field in *OurServices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *OurServices → Items*
 */
export interface OurServicesSliceDefaultItem {
  /**
   * subHeading field in *OurServices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Description field in *OurServices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * extendedDescription field in *OurServices → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].extendeddescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  extendeddescription: prismic.RichTextField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurServicesSliceDefaultPrimary>,
  Simplify<OurServicesSliceDefaultItem>
>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault;

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSlice = prismic.SharedSlice<
  "our_services",
  OurServicesSliceVariation
>;

/**
 * Primary content in *Web3MarketingGuide → Primary*
 */
export interface Web3MarketingGuideSliceDefaultPrimary {
  /**
   * Heading field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * leftsubheading1 field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.leftsubheading1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leftsubheading1: prismic.RichTextField;

  /**
   * leftsubdescription1 field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.leftsubdescription1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leftsubdescription1: prismic.RichTextField;

  /**
   * leftsubheading2 field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.leftsubheading2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leftsubheading2: prismic.RichTextField;

  /**
   * leftsubdescription2 field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.leftsubdescription2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leftsubdescription2: prismic.RichTextField;

  /**
   * leftmaindescription field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.leftmaindescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  leftmaindescription: prismic.RichTextField;

  /**
   * rightheading field in *Web3MarketingGuide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.primary.rightheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rightheading: prismic.RichTextField;
}

/**
 * Primary content in *Web3MarketingGuide → Items*
 */
export interface Web3MarketingGuideSliceDefaultItem {
  /**
   * rightsubheading field in *Web3MarketingGuide → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.items[].rightsubheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rightsubheading: prismic.RichTextField;

  /**
   * rightdescription field in *Web3MarketingGuide → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: web3_marketing_guide.items[].rightdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rightdescription: prismic.RichTextField;
}

/**
 * Default variation for Web3MarketingGuide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Web3MarketingGuideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Web3MarketingGuideSliceDefaultPrimary>,
  Simplify<Web3MarketingGuideSliceDefaultItem>
>;

/**
 * Slice variation for *Web3MarketingGuide*
 */
type Web3MarketingGuideSliceVariation = Web3MarketingGuideSliceDefault;

/**
 * Web3MarketingGuide Shared Slice
 *
 * - **API ID**: `web3_marketing_guide`
 * - **Description**: Web3MarketingGuide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Web3MarketingGuideSlice = prismic.SharedSlice<
  "web3_marketing_guide",
  Web3MarketingGuideSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AllblogspageDocument,
      AllblogspageDocumentData,
      AllblogspageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataServicesFooterItem,
      FooterDocumentDataOfficialInfoFooterItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LandingpageDocument,
      LandingpageDocumentData,
      LandingpageDocumentDataSlicesSlice,
      MainarticleDocument,
      MainarticleDocumentData,
      MainarticleDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      TrendingarticleDocument,
      TrendingarticleDocumentData,
      TrendingarticleDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutusSlice,
      AboutusSliceDefaultPrimary,
      AboutusSliceVariation,
      AboutusSliceDefault,
      AllBlogsSlice,
      AllBlogsSliceDefaultPrimary,
      AllBlogsSliceDefaultItem,
      AllBlogsSliceVariation,
      AllBlogsSliceDefault,
      BlogSlice,
      BlogSliceDefaultPrimary,
      BlogSliceDefaultItem,
      BlogSliceVariation,
      BlogSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceDefaultItem,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      Hero2Slice,
      Hero2SliceDefaultPrimary,
      Hero2SliceImageRightPrimary,
      Hero2SliceVariation,
      Hero2SliceDefault,
      Hero2SliceImageRight,
      JoinourmissionSlice,
      JoinourmissionSliceDefaultPrimary,
      JoinourmissionSliceVariation,
      JoinourmissionSliceDefault,
      LandingpageHeroSlice,
      LandingpageHeroSliceDefaultPrimary,
      LandingpageHeroSliceVariation,
      LandingpageHeroSliceDefault,
      LandingpageSection3Slice,
      LandingpageSection3SliceDefaultPrimary,
      LandingpageSection3SliceDefaultItem,
      LandingpageSection3SliceVariation,
      LandingpageSection3SliceDefault,
      LandingpageSection4Slice,
      LandingpageSection4SliceDefaultPrimary,
      LandingpageSection4SliceVariation,
      LandingpageSection4SliceDefault,
      Landingpagesection2Slice,
      Landingpagesection2SliceDefaultPrimary,
      Landingpagesection2SliceVariation,
      Landingpagesection2SliceDefault,
      OurServicesSlice,
      OurServicesSliceDefaultPrimary,
      OurServicesSliceDefaultItem,
      OurServicesSliceVariation,
      OurServicesSliceDefault,
      Web3MarketingGuideSlice,
      Web3MarketingGuideSliceDefaultPrimary,
      Web3MarketingGuideSliceDefaultItem,
      Web3MarketingGuideSliceVariation,
      Web3MarketingGuideSliceDefault,
    };
  }
}
