import type { Metadata } from 'next'
import clsx from 'clsx'
import { Inter,Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { createClient } from '@/prismicio'

const inter = Inter({ subsets: ['latin'] })

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta-sans',
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export async function generateMetadata(): Promise<Metadata> {
  const client = createClient();

  const page = await client.getSingle("settings");

  return {
    title: page.data.site_title || "FocusWeb3",
    description: page.data.meta_description || "FocusWeb3 is a marketing/sales company for crypto businesses.",
    openGraph: {
      images: [page.data.og_image.url || ""],
    },
  }
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(inter.className,plusJakartaSans.variable)}>
      <body >

        <header>
          Header! 
        </header>

        {children} 

        <footer>
          Footer! 
        </footer>

        </body>
    </html>
  )
}
