import type { Metadata } from 'next'
import clsx from 'clsx'
import { Inter,Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { createClient } from '@/prismicio'

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ['400', '700','200','500'],
  subsets: ['latin'],
  // variable: '--font-plus-jakarta-sans',
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export async function generateMetadata(): Promise<Metadata> {
  const client = createClient();

  const settings = await client.getSingle("settings");

  return {
    title: settings.data.site_title || "FocusWeb3",
    description: settings.data.meta_description || "FocusWeb3 is a marketing/sales company for crypto businesses.",
    openGraph: {
      images: [settings.data.og_image.url || ""],
    },
  }
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <html lang='en'>
    <html lang="en" className={clsx(plusJakartaSans.className)} >
      <body className='bg-[#010101] text-white'>

        <Header />

        {children} 

        <Footer />

        </body>
    </html>
  )
}
